
services:
  resourceserver-lb:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/resourceserver.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - resourceserver01
      - resourceserver02

  usageserver-lb:
    image: nginx:latest
    ports:
      - "8090:8090"
    volumes:
      - ./nginx/usageserver.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - usageserver01
      - usageserver02

  resourceserver01:
    image: distributedcounter:latest
    command:
      - --config=/app/app-docker.yml
      - resourceserver
      - --port=8081
    ports:
      - "8081:8081"

  resourceserver02:
    image: distributedcounter:latest
    command:
      - --config=/app/app-docker.yml
      - resourceserver
      - --port=8082
    ports:
      - "8082:8082"

  usageserver01:
    image: distributedcounter:latest
    command:
      - --config=/app/app-docker.yml
      - usageserver
      - --port=8091
    ports:
      - "8091:8091"

  usageserver02:
    image: distributedcounter:latest
    command:
      - --config=/app/app-docker.yml
      - usageserver
      - --port=8092
    ports:
      - "8092:8092"
