services:

  db:
    image: postgres:15.15-trixie
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_DATABASE=usage
    volumes:
      - ./docker-infra/postgres/init-db:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d usage -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  db-migrate:
    image: migrate/migrate:4
    volumes:
      - ./migrations/usage:/migrations
    depends_on:
      db:
        condition: service_healthy
    command:
      - -path=/migrations
      - -database=postgres://postgres:postgres@db:5432/usage?sslmode=disable
      - up

  lgtm:
    image: grafana/otel-lgtm
    ports:
      - "4317:4317"
      - "3000:3000"

  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"


  kafka1:
    image: apache/kafka:4.1.1
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: 'EmptNWtoR4GGWx-BH6nGLQ'
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./docker-infra/data/kafka1/data:/var/lib/kafka/data

  kafka-ui:
    image: kafbat/kafka-ui:latest
    container_name: kafka-cluster-ui
    ports:
      - "18080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9093
    depends_on:
      - kafka1

  jobmanager:
    image: flink:1.20.3-scala_2.12-java17
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: hashmap
        state.checkpoints.dir: file:///tmp/flink-checkpoints
    volumes:
      - ./docker-infra/data/flink_data:/tmp
      - ./docker-infra/flink/flink-sql-connector-kafka-3.3.0-1.20.jar:/opt/flink/lib/flink-sql-connector-kafka-3.3.0-1.20.jar

  taskmanager:
    image: flink:1.20.3-scala_2.12-java17
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        state.backend: hashmap
        state.checkpoints.dir: file:///tmp/flink-checkpoints
    volumes:
      - ./docker-infra/data/flink_data:/tmp
      - ./docker-infra/flink/flink-sql-connector-kafka-3.3.0-1.20.jar:/opt/flink/lib/flink-sql-connector-kafka-3.3.0-1.20.jar

  sql-gateway:
    image: flink:1.20.3-scala_2.12-java17
    depends_on:
      jobmanager:
        condition: service_started
    ports:
      - "8083:8083" # REST endpoint
    command: /opt/flink/bin/sql-gateway.sh start-foreground -Dsql-gateway.endpoint.rest.address=0.0.0.0
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
    volumes:
      - ./docker-infra/flink/flink-sql-connector-kafka-3.3.0-1.20.jar:/opt/flink/lib/flink-sql-connector-kafka-3.3.0-1.20.jar

  sql-client:
    image: flink:1.20.3-scala_2.12-java17
    command: bin/sql-client.sh
    depends_on:
      - jobmanager
    volumes:
      - ./docker-infra/flink/flink-sql-connector-kafka-3.3.0-1.20.jar:/opt/flink/lib/flink-sql-connector-kafka-3.3.0-1.20.jar
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager


