
services:
  lgtm:
    image: grafana/otel-lgtm
    ports:
      - "4317:4317"
      - "3000:3000"

  rabbitmq-r1:
    image: rabbitmq:3-management
    volumes:
      - ./docker-infra/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./docker-infra/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./docker-infra/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq-r2:
    image: rabbitmq:3-management
    volumes:
      - ./docker-infra/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./docker-infra/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./docker-infra/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "25672:15672"
      - "35672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5

  db-r1:
    image: postgres:15.15-trixie
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_DATABASE=usage
    volumes:
      - ./docker-infra/postgres/init-db:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d usage -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  db-r1-migrate:
    image: migrate/migrate:4
    volumes:
      - ./migrations/usage:/migrations
    depends_on:
      db-r1:
        condition: service_healthy
    command:
      - -path=/migrations
      - -database=postgres://postgres:postgres@db-r1:5432/usage?sslmode=disable
      - up

  db-r2:
    image: postgres:15.15-trixie
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_DATABASE=usage
    volumes:
      - ./docker-infra/postgres/init-db:/docker-entrypoint-initdb.d
    ports:
      - "25432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d usage -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  db-r2-migrate:
    image: migrate/migrate:4
    volumes:
      - ./migrations/usage:/migrations
    depends_on:
      db-r1:
        condition: service_healthy
    command:
      - -path=/migrations
      - -database=postgres://postgres:postgres@db-r2:5432/usage?sslmode=disable
      - up

  resourceserver-lb:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./docker-infra/nginx/resourceserver-multiregion.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - resourceserver-r1-01
      - resourceserver-r1-02
      - resourceserver-r2-01
      - resourceserver-r2-02

  usageserver-lb:
    image: nginx:latest
    ports:
      - "8090:8090"
    volumes:
      - ./docker-infra/nginx/usageserver-multiregion.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - usageserver-r1-01
      - usageserver-r1-02
      - usageserver-r2-01
      - usageserver-r2-02

  resourceserver-r1-01:
    image: distributedcounter:latest
    command:
      - --config=/app/app.yml
      - resourceserver
      - --port=8081
    volumes:
      - ./app-docker-r1.yml:/app/app.yml
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: lgtm:4317
      OTEL_SDK_DISABLED: false
    ports:
      - "18081:8081"
    depends_on:
      rabbitmq-r1:
        condition: service_healthy

  resourceserver-r1-02:
    image: distributedcounter:latest
    command:
      - --config=/app/app.yml
      - resourceserver
      - --port=8082
    volumes:
      - ./app-docker-r1.yml:/app/app.yml
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: lgtm:4317
      OTEL_SDK_DISABLED: false
    ports:
      - "18082:8082"
    depends_on:
      rabbitmq-r1:
        condition: service_healthy

  resourceserver-r2-01:
    image: distributedcounter:latest
    command:
      - --config=/app/app.yml
      - resourceserver
      - --port=8081
    volumes:
      - ./app-docker-r2.yml:/app/app.yml
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: lgtm:4317
      OTEL_SDK_DISABLED: false
    ports:
      - "28081:8081"
    depends_on:
      rabbitmq-r2:
        condition: service_healthy

  resourceserver-r2-02:
    image: distributedcounter:latest
    command:
      - --config=/app/app.yml
      - resourceserver
      - --port=8082
    volumes:
      - ./app-docker-r2.yml:/app/app.yml
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: lgtm:4317
      OTEL_SDK_DISABLED: false
    ports:
      - "28082:8082"
    depends_on:
      rabbitmq-r2:
        condition: service_healthy

  usageserver-r1-01:
    image: distributedcounter:latest
    command:
      - --config=/app/app.yml
      - usageserver
      - --port=8091
      - --broker-queue=usagedata01
    volumes:
      - ./app-docker-r1.yml:/app/app.yml
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: lgtm:4317
      OTEL_SDK_DISABLED: false
    ports:
      - "18091:8091"
    depends_on:
      db-r1-migrate:
        condition: service_completed_successfully
      rabbitmq-r1:
        condition: service_healthy

  usageserver-r1-02:
    image: distributedcounter:latest
    command:
      - --config=/app/app.yml
      - usageserver
      - --port=8092
      - --broker-queue=usagedata02
    volumes:
      - ./app-docker-r1.yml:/app/app.yml
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: lgtm:4317
      OTEL_SDK_DISABLED: false
    ports:
      - "18092:8092"
    depends_on:
      db-r1-migrate:
        condition: service_completed_successfully
      rabbitmq-r1:
        condition: service_healthy

  usageserver-r2-01:
    image: distributedcounter:latest
    command:
      - --config=/app/app.yml
      - usageserver
      - --port=8091
      - --broker-queue=usagedata01
    volumes:
      - ./app-docker-r2.yml:/app/app.yml
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: lgtm:4317
      OTEL_SDK_DISABLED: false
    ports:
      - "28091:8091"
    depends_on:
      db-r2-migrate:
        condition: service_completed_successfully
      rabbitmq-r2:
        condition: service_healthy

  usageserver-r2-02:
    image: distributedcounter:latest
    command:
      - --config=/app/app.yml
      - usageserver
      - --port=8092
      - --broker-queue=usagedata02
    volumes:
      - ./app-docker-r2.yml:/app/app.yml
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: lgtm:4317
      OTEL_SDK_DISABLED: false
    ports:
      - "28092:8092"
    depends_on:
      db-r2-migrate:
        condition: service_completed_successfully
      rabbitmq-r2:
        condition: service_healthy
